micronaut:
  server:
    port: 6382
    cors:
      enabled: true
      configurations:
        default:
          # allowedOrigins: ["http://192.168.0.137:3000", "http://quran.bilalelhoudaigui.com"] # TODO: Make this flexible without breaking the app
          allowedOrigins: ["http://quran.bilalelhoudaigui.com"]
          allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allowedHeaders: ["*"]
          # Optional: if you need to allow credentials (cookies, authorization headers)
          allowCredentials: true
netty:
  default:
    allocator:
      max-order: 3

logging:
  level:
    root: INFO
    io.micronaut: DEBUG
